services:
  gravit-designer:
    container_name: gravit
    image: crocodilestick/gravitdesigner:latest
    build: .
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - PROJECTS_DIR=/data/projects
    volumes:
      - /docker/gravit/projects:/data/projects
    restart: unless-stopped
